I46 conductor weiym logger
Extensible-Clinical-Imaging-QC-Tool/ECIQC pull request #67
Opened 2023-01-25 09:41 UTC by martinjrobins

2023-01-31 23:23 UTC, weiym97 commented
I have added logging to the parser, and it works in unittest. So I'm going to merge my logger branch into i46 branch.

2023-02-01 10:17 UTC, ian-mcfarlane requested changes
MacOS tests are failing on a DCMTK error - we should look at this before merging, since they seem to pass on the i46-conductor branch.

![image](https://user-images.githubusercontent.com/92573875/216015495-7cd039fa-d77c-4922-b0c1-a42a834077a9.png)

2023-02-01 16:11 UTC, ian-mcfarlane approved these changes
Looks good to me - this looks fine to merge. I think it might be nice to add tests for the content of the log files produced (i.e., after a certain set of actions performed, does the log file accurately record what we expected). @weiym97 could this be added?

2023-02-08 16:23 UTC, ian-mcfarlane approved these changes

2023-02-15 09:47 UTC, merged